### ISSUE TITLE
running in browser grunt server 404 scripts/rootscope.js

### ISSUE THREAD

**Issue by arpu** [infomofo/cordova-angular-md-template#36]
running grunt serve  404 on rootscope.js script 
running grunt serve:dist  works fine but no clicks (template not changing for main view)  on sidebar works (chrome) 

sorry i'm a newbie with grunt

**Comment by arpu** [comment]
https://github.com/arpu/cordova-angular-md-template/commit/cfb1cf6e7be85b521f87c68ded65d5fa048d9e12

this fixed the Problem

**Comment by infomofo** [comment]
thanks for finding this @arpu - fixing it now
